apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot-service
spec:
  type: NodePort
  selector:
    app: demo-spring-boot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-boot-deployment
  labels:
    app: demo-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-spring-boot
  template:
    metadata:
      labels:
        app: demo-spring-boot
    spec:
      containers:
        - name: nginx
          image: champyevil/demo-spring-boot
          ports:
            - containerPort: 80